<?php

/**
 * BaseUtoconsultMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property integer $fromid
 * @property integer $toid
 * @property blob $content
 * @property boolean $isread
 * @property boolean $isdeleted
 * @property boolean $isvalid
 * @property UtoconsultUser $UtoconsultUser
 * 
 * @method string            getEmail()          Returns the current record's "email" value
 * @method integer           getFromid()         Returns the current record's "fromid" value
 * @method integer           getToid()           Returns the current record's "toid" value
 * @method blob              getContent()        Returns the current record's "content" value
 * @method boolean           getIsread()         Returns the current record's "isread" value
 * @method boolean           getIsdeleted()      Returns the current record's "isdeleted" value
 * @method boolean           getIsvalid()        Returns the current record's "isvalid" value
 * @method UtoconsultUser    getUtoconsultUser() Returns the current record's "UtoconsultUser" value
 * @method UtoconsultMessage setEmail()          Sets the current record's "email" value
 * @method UtoconsultMessage setFromid()         Sets the current record's "fromid" value
 * @method UtoconsultMessage setToid()           Sets the current record's "toid" value
 * @method UtoconsultMessage setContent()        Sets the current record's "content" value
 * @method UtoconsultMessage setIsread()         Sets the current record's "isread" value
 * @method UtoconsultMessage setIsdeleted()      Sets the current record's "isdeleted" value
 * @method UtoconsultMessage setIsvalid()        Sets the current record's "isvalid" value
 * @method UtoconsultMessage setUtoconsultUser() Sets the current record's "UtoconsultUser" value
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_message');
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fromid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('toid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content', 'blob', null, array(
             'type' => 'blob',
             'notnull' => true,
             ));
        $this->hasColumn('isread', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('isdeleted', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('isvalid', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UtoconsultUser', array(
             'local' => 'toid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}