<?php

/**
 * BaseUtoconsultAboutus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property blob $content
 * 
 * @method blob              getContent() Returns the current record's "content" value
 * @method UtoconsultAboutus setContent() Sets the current record's "content" value
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultAboutus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_aboutus');
        $this->hasColumn('content', 'blob', null, array(
             'type' => 'blob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}