<?php

/**
 * BaseUtoconsultTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $icon
 * @property string $keywords
 * 
 * @method string        getTitle()    Returns the current record's "title" value
 * @method string        getIcon()     Returns the current record's "icon" value
 * @method string        getKeywords() Returns the current record's "keywords" value
 * @method UtoconsultTag setTitle()    Sets the current record's "title" value
 * @method UtoconsultTag setIcon()     Sets the current record's "icon" value
 * @method UtoconsultTag setKeywords() Sets the current record's "keywords" value
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_tag');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('icon', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}