<?php

/**
 * BaseUtoconsultPhotoCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $category
 * @property string $keywords
 * @property Doctrine_Collection $UtoconsultPhoto
 * 
 * @method string                  getCategory()        Returns the current record's "category" value
 * @method string                  getKeywords()        Returns the current record's "keywords" value
 * @method Doctrine_Collection     getUtoconsultPhoto() Returns the current record's "UtoconsultPhoto" collection
 * @method UtoconsultPhotoCategory setCategory()        Sets the current record's "category" value
 * @method UtoconsultPhotoCategory setKeywords()        Sets the current record's "keywords" value
 * @method UtoconsultPhotoCategory setUtoconsultPhoto() Sets the current record's "UtoconsultPhoto" collection
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultPhotoCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_photo_category');
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UtoconsultPhoto', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}