<?php

/**
 * BaseUtoconsultAdvertisement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $title
 * @property string $content
 * @property string $link
 * @property string $photo
 * @property string $photoicon
 * @property integer $visitnumber
 * @property boolean $isdeleted
 * @property boolean $isvalid
 * @property UtoconsultUser $UtoconsultUser
 * 
 * @method integer                 getUserId()         Returns the current record's "user_id" value
 * @method string                  getTitle()          Returns the current record's "title" value
 * @method string                  getContent()        Returns the current record's "content" value
 * @method string                  getLink()           Returns the current record's "link" value
 * @method string                  getPhoto()          Returns the current record's "photo" value
 * @method string                  getPhotoicon()      Returns the current record's "photoicon" value
 * @method integer                 getVisitnumber()    Returns the current record's "visitnumber" value
 * @method boolean                 getIsdeleted()      Returns the current record's "isdeleted" value
 * @method boolean                 getIsvalid()        Returns the current record's "isvalid" value
 * @method UtoconsultUser          getUtoconsultUser() Returns the current record's "UtoconsultUser" value
 * @method UtoconsultAdvertisement setUserId()         Sets the current record's "user_id" value
 * @method UtoconsultAdvertisement setTitle()          Sets the current record's "title" value
 * @method UtoconsultAdvertisement setContent()        Sets the current record's "content" value
 * @method UtoconsultAdvertisement setLink()           Sets the current record's "link" value
 * @method UtoconsultAdvertisement setPhoto()          Sets the current record's "photo" value
 * @method UtoconsultAdvertisement setPhotoicon()      Sets the current record's "photoicon" value
 * @method UtoconsultAdvertisement setVisitnumber()    Sets the current record's "visitnumber" value
 * @method UtoconsultAdvertisement setIsdeleted()      Sets the current record's "isdeleted" value
 * @method UtoconsultAdvertisement setIsvalid()        Sets the current record's "isvalid" value
 * @method UtoconsultAdvertisement setUtoconsultUser() Sets the current record's "UtoconsultUser" value
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultAdvertisement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_advertisement');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('link', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('photo', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('photoicon', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('visitnumber', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('isdeleted', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('isvalid', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));


        $this->index('advertisementindex', array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UtoconsultUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'created_at',
              1 => 'title',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}