<?php

/**
 * BaseUtoconsultFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $category_id
 * @property string $title
 * @property string $keywords
 * @property string $description
 * @property string $file
 * @property string $file_original
 * @property integer $visitnumber
 * @property string $image
 * @property string $imageicon
 * @property string $lang
 * @property integer $level
 * @property boolean $isuto
 * @property string $type
 * @property boolean $isvalid
 * @property boolean $isdeleted
 * @property UtoconsultFileCategory $UtoconsultFileCategory
 * @property UtoconsultUser $UtoconsultUser
 * 
 * @method integer                getUserId()                 Returns the current record's "user_id" value
 * @method integer                getCategoryId()             Returns the current record's "category_id" value
 * @method string                 getTitle()                  Returns the current record's "title" value
 * @method string                 getKeywords()               Returns the current record's "keywords" value
 * @method string                 getDescription()            Returns the current record's "description" value
 * @method string                 getFile()                   Returns the current record's "file" value
 * @method string                 getFileOriginal()           Returns the current record's "file_original" value
 * @method integer                getVisitnumber()            Returns the current record's "visitnumber" value
 * @method string                 getImage()                  Returns the current record's "image" value
 * @method string                 getImageicon()              Returns the current record's "imageicon" value
 * @method string                 getLang()                   Returns the current record's "lang" value
 * @method integer                getLevel()                  Returns the current record's "level" value
 * @method boolean                getIsuto()                  Returns the current record's "isuto" value
 * @method string                 getType()                   Returns the current record's "type" value
 * @method boolean                getIsvalid()                Returns the current record's "isvalid" value
 * @method boolean                getIsdeleted()              Returns the current record's "isdeleted" value
 * @method UtoconsultFileCategory getUtoconsultFileCategory() Returns the current record's "UtoconsultFileCategory" value
 * @method UtoconsultUser         getUtoconsultUser()         Returns the current record's "UtoconsultUser" value
 * @method UtoconsultFile         setUserId()                 Sets the current record's "user_id" value
 * @method UtoconsultFile         setCategoryId()             Sets the current record's "category_id" value
 * @method UtoconsultFile         setTitle()                  Sets the current record's "title" value
 * @method UtoconsultFile         setKeywords()               Sets the current record's "keywords" value
 * @method UtoconsultFile         setDescription()            Sets the current record's "description" value
 * @method UtoconsultFile         setFile()                   Sets the current record's "file" value
 * @method UtoconsultFile         setFileOriginal()           Sets the current record's "file_original" value
 * @method UtoconsultFile         setVisitnumber()            Sets the current record's "visitnumber" value
 * @method UtoconsultFile         setImage()                  Sets the current record's "image" value
 * @method UtoconsultFile         setImageicon()              Sets the current record's "imageicon" value
 * @method UtoconsultFile         setLang()                   Sets the current record's "lang" value
 * @method UtoconsultFile         setLevel()                  Sets the current record's "level" value
 * @method UtoconsultFile         setIsuto()                  Sets the current record's "isuto" value
 * @method UtoconsultFile         setType()                   Sets the current record's "type" value
 * @method UtoconsultFile         setIsvalid()                Sets the current record's "isvalid" value
 * @method UtoconsultFile         setIsdeleted()              Sets the current record's "isdeleted" value
 * @method UtoconsultFile         setUtoconsultFileCategory() Sets the current record's "UtoconsultFileCategory" value
 * @method UtoconsultFile         setUtoconsultUser()         Sets the current record's "UtoconsultUser" value
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_file');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('file_original', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('visitnumber', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('imageicon', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('lang', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('isuto', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('isvalid', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('isdeleted', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));


        $this->index('fileindex', array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UtoconsultFileCategory', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('UtoconsultUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'created_at',
              1 => 'user_id',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}