<?php

/**
 * BaseUtoconsultFileCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $category
 * @property string $keywords
 * @property string $image
 * @property Doctrine_Collection $UtoconsultFile
 * 
 * @method string                 getCategory()       Returns the current record's "category" value
 * @method string                 getKeywords()       Returns the current record's "keywords" value
 * @method string                 getImage()          Returns the current record's "image" value
 * @method Doctrine_Collection    getUtoconsultFile() Returns the current record's "UtoconsultFile" collection
 * @method UtoconsultFileCategory setCategory()       Sets the current record's "category" value
 * @method UtoconsultFileCategory setKeywords()       Sets the current record's "keywords" value
 * @method UtoconsultFileCategory setImage()          Sets the current record's "image" value
 * @method UtoconsultFileCategory setUtoconsultFile() Sets the current record's "UtoconsultFile" collection
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultFileCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_file_category');
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UtoconsultFile', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}