<?php

/**
 * BaseUtoconsultSearchInput
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $content
 * @property UtoconsultUser $UtoconsultUser
 * 
 * @method integer               getUserId()         Returns the current record's "user_id" value
 * @method string                getContent()        Returns the current record's "content" value
 * @method UtoconsultUser        getUtoconsultUser() Returns the current record's "UtoconsultUser" value
 * @method UtoconsultSearchInput setUserId()         Sets the current record's "user_id" value
 * @method UtoconsultSearchInput setContent()        Sets the current record's "content" value
 * @method UtoconsultSearchInput setUtoconsultUser() Sets the current record's "UtoconsultUser" value
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultSearchInput extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_search_input');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UtoconsultUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}