<?php

/**
 * Basecity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cityID
 * @property string $city
 * @property integer $fatherID
 * 
 * @method integer getCityID()   Returns the current record's "cityID" value
 * @method string  getCity()     Returns the current record's "city" value
 * @method integer getFatherID() Returns the current record's "fatherID" value
 * @method city    setCityID()   Sets the current record's "cityID" value
 * @method city    setCity()     Sets the current record's "city" value
 * @method city    setFatherID() Sets the current record's "fatherID" value
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('city');
        $this->hasColumn('cityID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fatherID', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}