<?php

/**
 * BaseUtoconsultArticleCategory2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category1_id
 * @property integer $orders
 * @property string $name
 * @property string $keywords
 * @property UtoconsultArticleCategory1 $UtoconsultArticleCategory1
 * @property Doctrine_Collection $UtoconsultMyArticle
 * 
 * @method integer                    getCategory1Id()                Returns the current record's "category1_id" value
 * @method integer                    getOrders()                     Returns the current record's "orders" value
 * @method string                     getName()                       Returns the current record's "name" value
 * @method string                     getKeywords()                   Returns the current record's "keywords" value
 * @method UtoconsultArticleCategory1 getUtoconsultArticleCategory1() Returns the current record's "UtoconsultArticleCategory1" value
 * @method Doctrine_Collection        getUtoconsultMyArticle()        Returns the current record's "UtoconsultMyArticle" collection
 * @method UtoconsultArticleCategory2 setCategory1Id()                Sets the current record's "category1_id" value
 * @method UtoconsultArticleCategory2 setOrders()                     Sets the current record's "orders" value
 * @method UtoconsultArticleCategory2 setName()                       Sets the current record's "name" value
 * @method UtoconsultArticleCategory2 setKeywords()                   Sets the current record's "keywords" value
 * @method UtoconsultArticleCategory2 setUtoconsultArticleCategory1() Sets the current record's "UtoconsultArticleCategory1" value
 * @method UtoconsultArticleCategory2 setUtoconsultMyArticle()        Sets the current record's "UtoconsultMyArticle" collection
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultArticleCategory2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_article_category2');
        $this->hasColumn('category1_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('orders', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 15,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UtoconsultArticleCategory1', array(
             'local' => 'category1_id',
             'foreign' => 'id'));

        $this->hasMany('UtoconsultMyArticle', array(
             'local' => 'id',
             'foreign' => 'category2_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}