<?php

/**
 * BaseUtoconsultArticleCategory1
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $photo1
 * @property string $keywords
 * @property Doctrine_Collection $UtoconsultArticleCategory2
 * @property Doctrine_Collection $UtoconsultMyArticle
 * 
 * @method string                     getName()                       Returns the current record's "name" value
 * @method string                     getPhoto1()                     Returns the current record's "photo1" value
 * @method string                     getKeywords()                   Returns the current record's "keywords" value
 * @method Doctrine_Collection        getUtoconsultArticleCategory2() Returns the current record's "UtoconsultArticleCategory2" collection
 * @method Doctrine_Collection        getUtoconsultMyArticle()        Returns the current record's "UtoconsultMyArticle" collection
 * @method UtoconsultArticleCategory1 setName()                       Sets the current record's "name" value
 * @method UtoconsultArticleCategory1 setPhoto1()                     Sets the current record's "photo1" value
 * @method UtoconsultArticleCategory1 setKeywords()                   Sets the current record's "keywords" value
 * @method UtoconsultArticleCategory1 setUtoconsultArticleCategory2() Sets the current record's "UtoconsultArticleCategory2" collection
 * @method UtoconsultArticleCategory1 setUtoconsultMyArticle()        Sets the current record's "UtoconsultMyArticle" collection
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtoconsultArticleCategory1 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utoconsult_article_category1');
        $this->hasColumn('name', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 15,
             ));
        $this->hasColumn('photo1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UtoconsultArticleCategory2', array(
             'local' => 'id',
             'foreign' => 'category1_id'));

        $this->hasMany('UtoconsultMyArticle', array(
             'local' => 'id',
             'foreign' => 'category1_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}