<?php

/**
 * areaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class areaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object areaTable
     */
	public static $areas=array();
    public static function getInstance()
    {
        return Doctrine_Core::getTable('area');
    }
    
    public function getArea($cityID){
    	 $array=$this->createQuery('a')->where('a.fatherID = ?',$cityID)->fetchArray();
    	 self::$areas[0]='地区';
    	 foreach ($array as $element) {
    	 	self::$areas[$element['areaID']]=$element['area'];
    	 }

    	 return self::$areas;
    }
    
}