<?php

/**
 * area
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class area extends Basearea
{
	public static function getAreaByCityId($cityId){
	
		$q = Doctrine_Query::create()
             ->from('area a')
             ->where('a.fatherID = ?',$cityId); 
        return $q->fetchArray();     

	}
    
	
    public static function getAreaById($areaId){
		$q = Doctrine_Query::create()
             ->from('area a')
             ->where('a.areaID = ?',$areaId); 
        return $q->fetchOne();   
	}
}