<?php

/**
 * cityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class cityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object cityTable
     */
	public static $citys=array();
    public static function getInstance()
    {
        return Doctrine_Core::getTable('city');
    }
    
    public function getCity($provinceID){
    	 $array=$this->createQuery('c')->where('c.fatherID = ?',$provinceID)->fetchArray();
    	 self::$citys[0]='市';
    	 foreach ($array as $element) {
    	 	self::$citys[$element['cityID']]=$element['city'];
    	 }

    	 return self::$citys;
    }
}