<?php

/**
 * province
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class province extends Baseprovince
{
	public static function getProvinceById($provinceId){
		$q = Doctrine_Query::create()
             ->from('province p')
             ->where('p.provinceID = ?',$provinceId); 
        return $q->fetchOne();   
	}
	
	public static function getProvinceCityAreaExport(){
		$q = Doctrine_Query::create()
             ->from('province p');
        return $q->fetchArray();     
	}

}