<?php

/**
 * UtoconsultPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UtoconsultPhoto extends BaseUtoconsultPhoto
{
	public static function getPhotoByCategory($category_id = null,$user_id = null){
		$q = Doctrine_Query::create()
		     ->from('UtoconsultPhoto up')
             ->leftJoin('up.UtoconsultPhotoCategory upc')
             ->leftJoin('up.UtoconsultUser uu');
             
		if ($category_id){
           $q->addWhere('up.category_id = ? ',$category_id);
		}
		
		if ($user_id){
           $q->addWhere('uu.user_id = ? ',$user_id);
		}
		
		return $q;
	}

}