<?php

/**
 * UtoconsultSearchInputTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultSearchInputTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultSearchInputTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultSearchInput');
    }
}