<?php

/**
 * UtoconsultAdvertisementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultAdvertisementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultAdvertisementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultAdvertisement');
    }
}