<?php

/**
 * UtoconsultUserInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultUserInformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultUserInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultUserInformation');
    }
}