<?php

/**
 * UtoconsultTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultTag');
    }
}