<?php

/**
 * UtoconsultArticleCategory2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    utoconsult
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UtoconsultArticleCategory2 extends BaseUtoconsultArticleCategory2
{
	public static function getCategorys($category2 = null, $category1 = null){
		$q = Doctrine_Query::create();
		    if (!$category1 && $category2)
        	 $q->from('UtoconsultArticleCategory2 u')
             ->leftJoin('u.UtoconsultArticleCategory1 u2');
             
            if ($category1 && !$category2)
             $q->from('UtoconsultArticleCategory1 u2');
             
            if ($category2) 
             $q->where('u.id=?',$category2);
            if ($category1) 
             $q->where('u2.id=?',$category1); 
        return $q->fetchArray();     
	}
	
	
	public static function getCategory2ByCategory1($category1){
		$q = Doctrine_Query::create()
        	 ->from('UtoconsultArticleCategory2 u')
        	 ->leftJoin('u.UtoconsultArticleCategory1 u2')
             ->where('u.category1_id=?',$category1);
        return $q->fetchArray();  
	}
	
}
