<?php

/**
 * UtoconsultUserInformation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    utoconsult
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UtoconsultUserInformation extends BaseUtoconsultUserInformation
{
	public static function getUtoconsultUserInformationById($request_id){
		$q = Doctrine_Query::create()
             ->from('UtoconsultUserInformation uinfo')
             ->leftJoin('uinfo.UtoconsultUser u')	
             ->leftJoin('u.UtoconsultUserProfilePhoto uupp')
             ->where('uinfo.user_id = ?',$request_id);
        return $q->fetchOne();  
	}
	
	public static function getUtoconsultUserInformationByUsername($request_username){
		$q = Doctrine_Query::create()
             ->from('UtoconsultUserInformation uinfo')
             ->leftJoin('uinfo.UtoconsultUser u')	
             ->leftJoin('u.UtoconsultUserProfilePhoto uupp')
             ->where('u.username = ?',$request_username);
        return $q->fetchOne();  
	}
}
