<?php

/**
 * UtoconsultUserContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultUserContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultUserContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultUserContact');
    }
}