<?php

/**
 * UtoconsultUserContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    utoconsult
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UtoconsultUserContact extends BaseUtoconsultUserContact
{
	public static function getUtoconsultUserContactById($request_id){
		$q = Doctrine_Query::create()
             ->from('UtoconsultUserContact ucon')
             ->leftJoin('ucon.UtoconsultUser u')
             ->where('ucon.user_id = ?',$request_id);
        return $usercon=$q->fetchOne();  
	}
	
	public static function getUtoconsultUserContactByUsername($request_username){
		$q = Doctrine_Query::create()
		     ->from('UtoconsultUserContact ucon')
		     ->leftJoin('ucon.UtoconsultUser u')
		     ->where('u.username = ?',$request_username);
		     $usercon=$q->fetchOne();

		return $usercon;       

	}
	
}
