<?php

/**
 * UtoconsultSearchInput
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UtoconsultSearchInput extends BaseUtoconsultSearchInput
{
  public static function addSearchInput($input,$user_id){
  	$searchinput=new UtoconsultSearchInput();
  	$searchinput->setContent($input);
  	$searchinput->setUserId($user_id);
  	$searchinput->save();
  	
  }
}