<?php

/**
 * UtoconsultArticleCategory1
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    utoconsult
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UtoconsultArticleCategory1 extends BaseUtoconsultArticleCategory1
{
	public static function getCategory1Category2(){
		$q = Doctrine_Query::create()
		     ->from('UtoconsultArticleCategory2 u2')
		     ->leftJoin('u2.UtoconsultArticleCategory1 u')
		     ->orderBy('u2.orders')
		     ->addOrderBy('u2.id');
		return $q->fetchArray(); 
	}
}
