<?php

/**
 * UtoconsultFileCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultFileCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultFileCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultFileCategory');
    }
}