<?php

/**
 * UtoconsultMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultMessage');
    }
}