<?php

/**
 * UtoconsultContactusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultContactusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultContactusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultContactus');
    }
}