<?php

/**
 * UtoconsultPublicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultPublicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultPublicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultPublication');
    }
}