<?php

/**
 * UtoconsultUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultUser');
    }
}