<?php

/**
 * UtoconsultArticleCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultArticleCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultArticleCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultArticleComment');
    }
}