<?php

/**
 * UtoconsultArticleCategory2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultArticleCategory2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultArticleCategory2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultArticleCategory2');
    }
}