<?php

/**
 * UtoconsultMyArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UtoconsultMyArticle extends BaseUtoconsultMyArticle
{

        public function setSlug($slug){	
		return $this->_set('slug', md5($slug));
	}
   

	
	public static function getArticleByCategory2($category2 = null, $category1 = null, $article_id = null){
	$q = Doctrine_Query::create()
             ->select('id','title','photo1','uac1.name')       
             ->from('UtoconsultMyArticle uma')
             ->leftJoin('uma.UtoconsultArticleCategory2 uac2')
             ->leftJoin('uma.UtoconsultArticleCategory1 uac1')
             ->orderBy('uma.updated_at DESC');
        if ($category1){
        	$q->addWhere('uac2.category1_id = ?',$category1);   
        } 
             
        if ($category2){
        	$q->addWhere('uma.category2_id = ?',$category2);     
        }
        
        if($article_id){
        	$q->addWhere('uma.id != ?',$article_id);
        }
        
        $q->addWhere('uma.isdeleted != 1');
        return $q;
	}
	
	public static function getArticleByCategory2Max($category2=null,$category1=null,$max = 10){
		$q=self::getArticleByCategory2($category2,$category1)->limit($max);
		return $q->execute();
	}
	
    public static function countTotal($category2){
		return self::getArticleByCategory2($category2)->count();
	}

	
	public static function getArticleById($id){
	 
		$q = Doctrine_Query::create()
		     ->from('UtoconsultMyArticle u2')
		     ->leftJoin('u2.UtoconsultUser uu')
                     ->leftJoin('uu.UtoconsultUserInformation uui')
		     ->leftJoin('u2.UtoconsultArticleCategory2 uac2')
                     ->leftJoin('uac2.UtoconsultArticleCategory1 uac1')
		     ->where('u2.id = ?',$id);
		$q->addWhere('u2.isdeleted != 1');     
		return $q->fetchOne();     
     
	}
	
	public static function getNextArticleById($id){
		$q = Doctrine_Query::create()
		     ->from('UtoconsultMyArticle u2')
		     ->where('u2.id > ?',$id);
		$q->addWhere('u2.isdeleted != 1');  
		$q->limit(1);
		
		return $q->fetchOne();   
	}
	
    public static function getPrevArticleById($id){
		$q = Doctrine_Query::create()
		     ->from('UtoconsultMyArticle u2')
		     ->where('u2.id < ?',$id)
		     ->orderBy('u2.id DESC');
		$q->addWhere('u2.isdeleted != 1');  
		$q->limit(1);
		
		return $q->fetchOne();   
	}
	
	public static function getArticleBySlug($slug){
		$q = Doctrine_Query::create()
		     ->from('UtoconsultMyArticle u2')
		     ->where('u2.slug = ?',$slug);
		$q->addWhere('u2.isdeleted != 1');     
		return $q->fetchOne();   
	}

	
	
public function save(Doctrine_Connection $conn = null)
{

  
  $conn = $conn ? $conn : $this->getTable()->getConnection();
  $conn->beginTransaction();
  try
  {
    $ret = parent::save($conn);
 
    $this->updateLuceneIndex();
 
    $conn->commit();
 
    return $ret;
  }
  catch (Exception $e)
  {
    $conn->rollBack();
  }
  
}

 





public function delete(Doctrine_Connection $conn = null)
{
	$index = UtoconsultMyArticleTable::getLuceneIndex();

	foreach ($index->find('article_cn_pk:'.$this->getId()) as $hit)
	{
		$index->delete($hit->id);
	}

	return parent::delete($conn);
}


public function updateLuceneIndex()
{
  $index = UtoconsultMyArticleTable::getLuceneIndex();
 

  foreach ($index->find('article_cn_pk:'.$this->getId()) as $hit)
  {
    $index->delete($hit->id);
  }
  setlocale(LC_ALL, 'zh-cn.UTF-8');
  require_once sfConfig::get('sf_lib_dir').'/vendor/Zend/Search/Lucene/Analysis/CN_Lucene_Analyzer.php';
  Zend_Search_Lucene_Analysis_Analyzer::setDefault( new CN_Lucene_Analyzer() ); 
  
  $doc = new Zend_Search_Lucene_Document();
 
  // store article primary key to identify it in the search results
  $doc->addField(Zend_Search_Lucene_Field::Keyword('article_cn_pk', $this->getId()));
 
  // index article fields    //UnStored
  $doc->addField(Zend_Search_Lucene_Field::text('title', $this->getTitle(), 'utf-8'));
  $doc->addField(Zend_Search_Lucene_Field::text('category1', $this->getUtoconsultArticleCategory1()->getName(), 'utf-8'));
  $doc->addField(Zend_Search_Lucene_Field::text('category2', $this->getUtoconsultArticleCategory2()->getName(), 'utf-8'));
  $doc->addField(Zend_Search_Lucene_Field::text('keywords', $this->getKeywords(), 'utf-8'));
  
  
  
  // add job to the index
  $index->addDocument($doc);
  $index->commit();
}



}