<?php

/**
 * UtoconsultAboutusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultAboutusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultAboutusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultAboutus');
    }
}