<?php

/**
 * UtoconsultArticleCategory1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultArticleCategory1Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultArticleCategory1Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultArticleCategory1');
    }
}