<?php

/**
 * UtoconsultPhotoCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultPhotoCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultPhotoCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultPhotoCategory');
    }
}