<?php

/**
 * UtoconsultAnnoncementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultAnnoncementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultAnnoncementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultAnnoncement');
    }
}