<?php

/**
 * UtoconsultPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultPhoto');
    }
}