<?php

/**
 * UtoconsultFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UtoconsultFile extends BaseUtoconsultFile
{
   public static function getFiles($userid = null,$category = null){
   	$q = Doctrine_Query::create()
   	     ->from('UtoconsultFile uf')
   	     ->leftJoin('uf.UtoconsultUser uu')
   	     ->leftJoin('uu.UtoconsultUserInformation uui')
         ->orderBy('uf.updated_at DESC')
         ->where('uf.isdeleted != 1');
         
    if($userid){
   	     	$q->addWhere('uf.user_id = ?',$userid);
   	}
   	
   	if($category){
   		    $q->addWhere('uf.category_id = ?',$category);
   	}
   	
   	return $q;     
   }
   
   
/*   
public function save(Doctrine_Connection $conn = null)
{

  
  $conn = $conn ? $conn : $this->getTable()->getConnection();
  $conn->beginTransaction();
  try
  {
    $ret = parent::save($conn);
 
    $this->updateLuceneIndex();
 
    $conn->commit();
 
    return $ret;
  }
  catch (Exception $e)
  {
    $conn->rollBack();
  }
  
}

 


public function delete(Doctrine_Connection $conn = null)
{
  $index = UtoconsultMyArticleTable::getLuceneIndex();
 
  foreach ($index->find('file_pk:'.$this->getId()) as $hit)
  {
    $index->delete($hit->id);
  }
 
  return parent::delete($conn);
}



public function updateLuceneIndex()
{
  $index = UtoconsultMyArticleTable::getLuceneIndex();
 

  foreach ($index->find('file_pk:'.$this->getId()) as $hit)
  {
    $index->delete($hit->id);
  }
  setlocale(LC_ALL, 'zh-cn.UTF-8');
  require_once sfConfig::get('sf_lib_dir').'/vendor/Zend/Search/Lucene/Analysis/CN_Lucene_Analyzer.php';
  Zend_Search_Lucene_Analysis_Analyzer::setDefault( new CN_Lucene_Analyzer() ); 
  
  $doc = new Zend_Search_Lucene_Document();
 
  // store article primary key to identify it in the search results
  $doc->addField(Zend_Search_Lucene_Field::Keyword('file_pk', $this->getId()));
 
  // index article fields    //UnStored
  $doc->addField(Zend_Search_Lucene_Field::text('title', $this->getTitle(), 'utf-8'));
  $doc->addField(Zend_Search_Lucene_Field::text('keywords', $this->getKeywords(), 'utf-8'));
  $doc->addField(Zend_Search_Lucene_Field::text('description', $this->getDescription(), 'utf-8'));
  $doc->addField(Zend_Search_Lucene_Field::text('type', 'article', 'utf-8'));

 
  // add job to the index
  $index->addDocument($doc);
  $index->commit();
}
   */
   
}