<?php

/**
 * UtoconsultFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultFile');
    }
}