<?php

/**
 * UtoconsultUserProfilePhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtoconsultUserProfilePhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtoconsultUserProfilePhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtoconsultUserProfilePhoto');
    }
}